[+special:strings]
HFS=HFS
Uptime=稼働時間
Account panel=アカウントパネル
Login=ログイン
Search=検索
Enable multi-selection=複数選択を有効にする
Selection=選択
New folder=新しいフォルダー
Display timestamps=タイムスタンプを表示する
Toggle timestamp=タイムスタンプを切り替え
Upload=アップロード
Change list order=リストの並べ替えを変更する
Sort=並べ替え
selected=選択済み
Mask=マスク
Invert=選択を反転
Delete=削除
Move=移動
Download selected files as a single archive=選択したファイルを単一のアーカイブとしてダウンロードする
Archive=アーカイブ
title=タイトル
folders=フォルダー
files=ファイル
Uploaded=アップロードされました
Failed=失敗
Queued=キュー待ち
Uploading...=アップロード中...
Reload page=ページをリロードする
this folder and sub-folders=このフォルダーとサブフォルダー
this folder only=このフォルダーのみ
entire server=サーバー全体
Go=移動
Search field is mandatory=検索フィールドは必須です
Download counter:=ダウンロード数:
NEW=新規
More options=その他のオプション
item folder=項目フォルダー
Login required=ログインが必要です
Not found=見つかりません
go to root=ルートへ移動
Server Too Busy=サーバーが混雑しています
The server is too busy to handle your request at this time. Retry later=現在、サーバーがビジー状態であるため、リクエストを処理できません。後でもう一度試してください
retry later=後でもう一度試してください
Download limit=ダウンロード制限
max s dl msg=ダウンロード制限に達しました。後でもう一度試してください
Unauthorized=認証されていません
Either your user name and password do not match, or you are not permitted to access this resource.=ユーザー名とパスワードが一致しないか、このリソースにアクセスする権限がありません。
Forbidden=アクセス禁止
This resource is not accessible.=このリソースにはアクセスできません。
You are banned=あなたは禁止されています
uploaded by=アップロード者
%reason%=%reason%
username not found=ユーザー名が見つかりません
download forbidden=ダウンロード禁止
No file exchange in progress.=現在進行中のファイル転送はありません。
No files=ファイルがありません
No results=結果はありません
no files=このフォルダーにはファイルがありません
no results=検索条件に一致する項目はありません
Uploading=アップロード中
Time left=残り時間
Downloading=ダウンロード中
User=ユーザー
created folder=フォルダーを作成しました
Anonymous=匿名
renamed=名前が変更されました
to=へ
Moving items to=アイテムの移動先
not found=見つかりません
already exists=すでに存在します
not moved=移動しませんでした
option.newfolder=新しいフォルダー
option.comment=コメント
option.rename=名前の変更
option.move=移動
Bytes=バイト
Ok=OK
ok=成功
Error=エラー
failed=失敗
Username=ユーザー名
Password=パスワード
Sorry, you lack permissions for this action=申し訳ありませんが、このアクションを実行する権限がありません
Warning: the password will be sent unencrypted to the server. For better security change the password from HFS window.=警告: パスワードは暗号化されずにサーバーに送信されます。セキュリティを強化するには、HFS ウィンドウからパスワードを変更します。
Enter new password=新しいパスワードを入力してください
Password changed=パスワードが変更されました
Cancel=キャンセル
confirm=確認する
Enter the destination folder=移動先フォルダーを入力
We met the following problems:=次の問題が発生しました:
files were moved.=ファイルが移動されました。
No file was moved.=ファイルは移動されませんでした。
Please enter the file mask to select=選択するファイルマスクを入力してください
Change password=パスワードを変更
Logout=ログアウト
Sort by=並べ替え基準
Size=サイズ
Speed=速度
Name=名前
Extension=拡張子
Timestamp=タイムスタンプ
Hits=ヒット数
Default=既定
You need to select some files first=先にファイルを選択してください
Rename=名前の変更
Comment=コメント
Downloading many files as archive can be a lengthy operation, and the result is a TAR file. Continue?=複数のファイルをアーカイブとしてダウンロードすると時間がかかる場合があり、結果のファイルは TAR ファイルになります。続けますか?
No access=アクセス権なし
UP=上へ
404 -  Not found=404 - 見つかりません
Server busy=サーバーが混雑しています
Please, retry later.=後でもう一度試してください。
Invalid server reply=無効なサーバー応答
communication error=通信エラー
close=閉じる
