[+special:strings]
HFS=HFS
Uptime=运作时间
Account panel=账号面板
Login=登录
Search=搜索
Enable multi-selection=启用多选
Selection=选择
New folder=新建文件夹
Display timestamps=显示时间戳
Toggle timestamp=切换时间戳
Upload=上传
Change list order=更改列表排序
Sort=排序
selected=已选择
Mask=遮罩
Invert=反向选择
Delete=删除
Move=移动
Download selected files as a single archive=将选中的文件下载为单个压缩包
Archive=压缩包
title=标题
folders=文件夹
files=文件
Uploaded=已上传
Failed=失败
Queued=队列中
Uploading...=上传中...
Reload page=重新加载页面
this folder and sub-folders=此文件夹和子文件夹
this folder only=仅此文件夹
entire server=整个服务器
Go=前往
Search field is mandatory=搜索字段为必填
Download counter:=下载计数：
NEW=新
More options=更多选项
item folder=项目文件夹
Login required=需要登录
Not found=找不到
go to root=前往根目录
Server Too Busy=服务器过于忙碌
The server is too busy to handle your request at this time. Retry later=服务器当前过于忙碌，无法处理你的请求。请稍后重试
retry later=请稍后重试
Download limit=下载限制
max s dl msg=已达到下载限制。请稍后重试
Unauthorized=未授权
Either your user name and password do not match, or you are not permitted to access this resource.=你的用户名和密码不匹配，或你没有权限访问此资源。
Forbidden=禁止访问
This resource is not accessible.=此资源无法访问。
You are banned=你已被封禁
uploaded by=上传者
%reason%=%reason%
username not found=找不到用户名
download forbidden=禁止下载
No file exchange in progress.=当前没有正在进行的文件传输。
No files=没有文件
No results=没有结果
no files=此文件夹没有文件
no results=没有符合搜索条件的项目
Uploading=上传中
Time left=剩余时间
Downloading=下载中
User=用户
created folder=已创建文件夹
Anonymous=匿名
renamed=已重新命名
to=为
Moving items to=正在移动项目到
not found=找不到
already exists=已存在
not moved=未移动
option.newfolder=新建文件夹
option.comment=备注
option.rename=重新命名
option.move=移动
Bytes=字节
Ok=确定
ok=成功
Error=错误
failed=失败
Username=用户名
Password=密码
Sorry, you lack permissions for this action=抱歉，你没有执行此操作的权限
Warning: the password will be sent unencrypted to the server. For better security change the password from HFS window.=警告：密码将以未加密方式发送到服务器。为了提高安全性，请从 HFS 窗口更改密码。
Enter new password=输入新密码
Password changed=密码已变更
Cancel=取消
confirm=确认
Enter the destination folder=输入目标文件夹
We met the following problems:=遇到以下问题：
files were moved.=文件已移动。
No file was moved.=没有移动任何文件。
Please enter the file mask to select=请输入要选择的文件掩码
Change password=变更密码
Logout=登出
Sort by=排序依据
Size=大小
Speed=速度
Name=名称
Extension=扩展名
Timestamp=时间戳
Hits=点击数
Default=默认
You need to select some files first=你需要先选择一些文件
Rename=重新命名
Comment=备注
Downloading many files as archive can be a lengthy operation, and the result is a TAR file. Continue?=将多个文件下载为压缩包可能需要较长时间，生成的文件会是 TAR 文件。要继续吗？
No access=无访问权限
UP=上一层
404 -  Not found=404 - 找不到
Server busy=服务器忙碌
Please, retry later.=请稍后重试。
Invalid server reply=服务器响应无效
communication error=通信错误
close=关闭
